<?php


abstract class Animal{
    public $name;
    public $color;
    public function describe(){
        return 'this  dog named ' .$this->name . ' is ' . $this->color;
    }

    abstract public function makeSound();

};

class Dog extends  Animal{
    public function describe(){
        return  parent::describe(); // TODO: Change the autogenerated stub
    }
    public function  makeSound(){
        return 'barks';
    }
};
$animal = new Dog();
$animal->name = 'bobby';
$animal->color = 'grey';
echo $animal->describe();
?>