<?php
//    class User{
//        public $id;
//        public $userName;
//        public $email;
//        public $password;
//
//        public function __construct(){
//
//            echo 'Constructor Called <br>';
//        }
//
//        public function register(){
//            echo 'User Registered </br>';
//
//        }
//        public function login($userName,$password){
//               $this->auth_user($userName,$password);
//            }
//
//        public function auth_user($userName,$password){
//            echo $userName . ' is authenticated<br>';
//        }
//        public function __destruct(){
//            // TODO: Implement __destruct() method.
//        }
//    }
//
//
//    $User = new User();
//    $User->register();
//    $User->login('Timi','2345');
//
//
//
//
//?>
<?php
//    class Post{
//        private $name;
//        public function __set($name, $value){
//            echo 'Setting '. $name . ' to ' . $value . '<br>';
//            $this->$name = $value;
//
//        }
//        public function __get($name){
//            echo 'getting ' . $name . ' from '. $this->name . '<br>';
//        }
//
//
//    }
//$post = new Post;
//$post-> name = 'testing';
//echo $post->name;
//
//?>

<?


    abstact class Animal{
    public $name;
    public $color;
        public function describe(){
            return 'this ' .$this->name . ' is ' . $this->color;
        }

        abstract public function makeSound();

    };

     class Dog extends  Animal{
        public function describe(){
           return  parent::describe(); // TODO: Change the autogenerated stub
        }
        public function  makeSound(){
            return 'barks';
        }
    };
    $animal = new Dog();
    $animal->name = 'bobby';
    $animal->color = 'grey';
    echo $animal->describe();
?>
